services:
  db:
    image: postgres:16.2
    container_name: api-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/data/db
      - ./src/db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: tasksdb

volumes:
  db_data: